C#/SocialGame/SocialGame/Models/Friendship.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SocialGame.Web.Models
{
    public class Friendship
    {

        public virtual int FriendshipId { get; set; }
        [Display(Name = "Strength", ResourceType = typeof(Resources.Resources))]
        public virtual int? Strength { get; set; }
        public virtual int UserProfileOneId { get; set; }
        public virtual int UserProfileTwoId { get; set; }
        public virtual bool IsFriend { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
    }
}

C#/SocialGame/SocialGame/Models/ViewModels/FriendshipViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SocialGame.Web.Models.ViewModels
{
    public class FriendshipViewModel
    {
        public UserProfile MyUserProfile { get; set; }

        public List<UserProfile> MyFriends { get; set; }

        public List<UserProfile> MyFriendFriends { get; set; }

        public List<UserProfile> FriendRequests { get; set; }

        public UserProfile FriendSuggestion { get; set; }

        public UserProfile MyFriendProfile { get; set; }

        public UserProfile MyFriendRequestProfile { get; set; }
    }
}

C#/SocialGame/SocialGame/Controllers/FriendshipController.cs
using SocialGame.Web.Abstract;
using SocialGame.Web.Enum;
using SocialGame.Web.Models;
using SocialGame.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace SocialGame.Web.Controllers
{
    public class FriendshipController : Controller
    {
        ISocialGameDataSource db;

        public FriendshipController(ISocialGameDataSource db)
        {
            this.db = db;
        }

        public ActionResult Index(string userName)
        {
            FriendshipViewModel friendshipViewModel = new FriendshipViewModel();

            friendshipViewModel.FriendRequests = new List<UserProfile>();

            friendshipViewModel.MyUserProfile = this.db.UserProfiles.Where(u => u.UserName == userName).FirstOrDefault();

            if(friendshipViewModel.MyUserProfile != null)
            {
                List<Friendship> friendships = this.db.Friendships.Where(f => f.UserProfileOneId == friendshipViewModel.MyUserProfile.UserId || f.UserProfileTwoId == friendshipViewModel.MyUserProfile.UserId).ToList();

                List<int> friendsUserIds = new List<int>();
                List<int> friendRequestsUserIds = new List<int>();

                foreach(Friendship friend in friendships)
                {
                    if(friend.IsFriend)
                    {
                        if(friend.UserProfileOneId != friendshipViewModel.MyUserProfile.UserId)
                        {
                            friendsUserIds.Add(friend.UserProfileOneId);
                        }
                        else
                        {
                            friendsUserIds.Add(friend.UserProfileTwoId);
                        }
                    }
                    else
                    {
                        if(friend.UserProfileTwoId == friendshipViewModel.MyUserProfile.UserId)
                        {
                            friendRequestsUserIds.Add(friend.UserProfileOneId);
                        }
                    }
                }

                friendshipViewModel.MyFriends = this.db.UserProfiles.Where(u => friendsUserIds.Contains(u.UserId)).ToList();
                friendshipViewModel.FriendRequests = this.db.UserProfiles.Where(u => friendRequestsUserIds.Contains(u.UserId)).ToList();
            }

            return View(friendshipViewModel);
        }

        public ActionResult IgnoreFriendRequest(int friendUserId, int myUserId, string myUserName)
        {
            Friendship friendship = this.db.Friendships.Where(f => f.UserProfileOneId == friendUserId && f.UserProfileTwoId == myUserId).FirstOrDefault();

            if(friendship != null)
            {
                this.db.DeleteFriendship(friendship);
                this.db.Save();
            }

            return RedirectToAction("Index", new { userName = myUserName });
        }

        public ActionResult DeleteFriend(int friendUserId, int myUserId, string myUserName)
        {
            Friendship friendship = this.db.Friendships.Where(f => f.UserProfileOneId == friendUserId && f.UserProfileTwoId == myUserId || f.UserProfileTwoId == friendUserId && f.UserProfileOneId == myUserId).FirstOrDefault();

            if(friendship != null)
            {
                this.db.DeleteFriendship(friendship);
                this.db.Save();
            }

            return RedirectToAction("Index", new { userName = myUserName });
        }

        public ActionResult AcceptFriendRequest(int friendUserId, int myUserId, string myUserName)
        {
            FriendshipRelationViewModel viewModel = new FriendshipRelationViewModel();

            viewModel.MyUserId = myUserId;
            viewModel.FriendUserId = friendUserId;
            viewModel.MyUserName = myUserName;

            viewModel.RelationTypes = new List<Enum.RelationType>();
            viewModel.RelationTypes.Add(Enum.RelationType.Unknown);
            viewModel.RelationTypes.Add(Enum.RelationType.Acquaintance);
            viewModel.RelationTypes.Add(Enum.RelationType.Colleague);
            viewModel.RelationTypes.Add(Enum.RelationType.Friend);
            viewModel.RelationTypes.Add(Enum.RelationType.Family);

            return View("ViewFriendshipRelation", viewModel);           
        }

        public ActionResult ConfirmFriendshipRelation(int friendUserId, int myUserId, string myUserName, RelationType relationType)
        {
            Friendship friendship = this.db.Friendships.Where(f => f.UserProfileOneId == friendUserId && f.UserProfileTwoId == myUserId).FirstOrDefault();

            if(friendship != null)
            {
                friendship.IsFriend = true;
                friendship.Strength = (int)relationType;
                this.db.UpdateFriendship(friendship);
                this.db.Save();
            }

            return RedirectToAction("Index", new { userName = myUserName });
        }

        public ActionResult ViewUserProfile(int friendUserId, int myUserId)
        {
            FriendshipViewModel friendshipViewModel = new FriendshipViewModel();

            friendshipViewModel.MyFriendRequestProfile = this.db.UserProfiles.Where(u => u.UserId == friendUserId).FirstOrDefault();

            friendshipViewModel.MyUserProfile = this.db.UserProfiles.Where(u => u.UserId == myUserId).FirstOrDefault();

            return View(friendshipViewModel);
        }

        public ActionResult ViewFriendProfile(int friendUserId, int myUserId)
        {
            FriendshipViewModel friendshipViewModel = new FriendshipViewModel();

            friendshipViewModel.MyFriendProfile = this.db.UserProfiles.Where(u => u.UserId == friendUserId).FirstOrDefault();

            friendshipViewModel.MyUserProfile = this.db.UserProfiles.Where(u => u.UserId == myUserId).FirstOrDefault();

            return View(friendshipViewModel);
        }

        public ActionResult ViewMyFriendFriends(int friendUserId, int myUserId)
        {
            FriendshipViewModel friendshipViewModel = new FriendshipViewModel();

            friendshipViewModel.MyFriendProfile = this.db.UserProfiles.Where(u => u.UserId == friendUserId).FirstOrDefault();

            friendshipViewModel.MyUserProfile = this.db.UserProfiles.Where(u => u.UserId == myUserId).FirstOrDefault();

            List<Friendship> friendships = this.db.Friendships.Where(f => f.UserProfileOneId == friendshipViewModel.MyFriendProfile.UserId || f.UserProfileTwoId == friendshipViewModel.MyFriendProfile.UserId).ToList();

            List<Friendship> myFriendships = this.db.Friendships.Where(f => f.UserProfileOneId == friendshipViewModel.MyUserProfile.UserId || f.UserProfileTwoId == friendshipViewModel.MyUserProfile.UserId).ToList();

            List<int> friendsUserIds = new List<int>();

            List<int> myFriendsUserIds = new List<int>();

            foreach(Friendship friend in friendships)
            {
                if(friend.IsFriend)
                {
                    if(friend.UserProfileOneId != friendshipViewModel.MyFriendProfile.UserId)
                    {
                        friendsUserIds.Add(friend.UserProfileOneId);
                    }
                    else
                    {
                        friendsUserIds.Add(friend.UserProfileTwoId);
                    }
                }
            }

            foreach(Friendship friend in myFriendships)
            {
                if(friend.IsFriend)
                {
                    if(friend.UserProfileOneId != friendshipViewModel.MyUserProfile.UserId)
                    {
                        myFriendsUserIds.Add(friend.UserProfileOneId);
                    }
                    else
                    {
                        myFriendsUserIds.Add(friend.UserProfileTwoId);
                    }
                }
            }

            friendshipViewModel.MyFriends = this.db.UserProfiles.Where(u => myFriendsUserIds.Contains(u.UserId)).ToList();
            friendshipViewModel.MyFriendFriends = this.db.UserProfiles.Where(u => friendsUserIds.Contains(u.UserId)).ToList();

            return View(friendshipViewModel);
        }

        public ActionResult SearchFriends(string searchSetting, string userName)
        {
            FriendSearchViewModel searchViewModel = new FriendSearchViewModel();

            searchViewModel.MyUserProfile = this.db.UserProfiles.Where(u => u.UserName == userName).FirstOrDefault();

            List<Friendship> myFriendships = this.db.Friendships.Where(f => f.UserProfileOneId == searchViewModel.MyUserProfile.UserId || f.UserProfileTwoId == searchViewModel.MyUserProfile.UserId).ToList();
            List<string> myFriendshipProfilesUsernames = new List<string>();

            foreach(Friendship friendship in myFriendships)
            {
                if(friendship.UserProfileOneId == searchViewModel.MyUserProfile.UserId)
                {
                    myFriendshipProfilesUsernames.Add(this.db.UserProfiles.Where(u => u.UserId == friendship.UserProfileTwoId).FirstOrDefault().UserName);
                }
                else
                {
                    myFriendshipProfilesUsernames.Add(this.db.UserProfiles.Where(u => u.UserId == friendship.UserProfileOneId).FirstOrDefault().UserName);
                }
            }

            IQueryable<UserProfile> userProfileQuery = this.db.UserProfiles.Where(u => u.UserName.Contains(searchSetting)
                || (u.FirstName != null && u.FirstName.Contains(searchSetting))
                || (u.LastName != null && u.LastName.Contains(searchSetting)));

            userProfileQuery = userProfileQuery.Where(u => u.UserName != userName);

            userProfileQuery = userProfileQuery.Where(u => !myFriendshipProfilesUsernames.Contains(u.UserName));

            searchViewModel.SearchResults = userProfileQuery.Distinct().ToList();

C#/SocialGame/SocialGame/Views/Friendship/Index.cshtml
@model SocialGame.Web.Models.ViewModels.FriendshipViewModel
@using SocialGame.Web.Resources
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jqueryval")

@Html.Partial("_FriendSearch", new SocialGame.Web.Models.ViewModels.FriendSearchViewModel() { MyUserProfile = Model.MyUserProfile})

<h2>@Resources.MyFriends</h2>
<ul>
@foreach(SocialGame.Web.Models.UserProfile friend in Model.MyFriends)
{
    <li>@Html.DisplayFor(modelItem => friend.UserName)   @Html.ActionLink(Resources.ViewProfile, "ViewFriendProfile", "Friendship", new { friendUserId = friend.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName },null) <p></p></li>  
    
}
</ul>
<h2>@Resources.FriendRequests</h2>

@if(Model.FriendRequests.Count > 0)
{
    foreach(SocialGame.Web.Models.UserProfile friend in Model.FriendRequests)
    {
        @Html.DisplayFor(modelItem => friend.UserName)
        @Html.ActionLink(Resources.ViewProfile, "ViewUserProfile", "Friendship", new { friendUserId = friend.UserId, myUserId = Model.MyUserProfile.UserId },null)
        @Html.ActionLink(Resources.Accept, "AcceptFriendRequest", "Friendship", new { friendUserId = friend.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName },null)
        @Html.ActionLink(Resources.Ignore, "IgnoreFriendRequest", "Friendship", new { friendUserId = friend.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName }, null)    
    }
}
else
{
    <text>@Resources.NoFriendRequests</text>
}

@if(Model.FriendSuggestion != null)
{
    <h2>@Resources.FriendSuggestion</h2>
    @Html.DisplayFor(model => model.FriendSuggestion.UserName)
}

C#/SocialGame/SocialGame/Views/Friendship/ViewFriendProfile.cshtml
@model SocialGame.Web.Models.ViewModels.FriendshipViewModel
@using SocialGame.Web.Resources

<h2>@Model.MyFriendProfile.UserName @Resources.Profile</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.FirstName)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.FirstName)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.LastName)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.LastName)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.Email)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.Email)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.Address)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.Address)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.Country)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.Country)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.City)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.City)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.ZipCode)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.ZipCode)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.BirthDate)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.BirthDate)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.Telephone)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.Telephone)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendProfile.Mood.Description)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendProfile.Mood.Description)
        </td>
    </tr>
    <tr>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(Resources.View+" " + Model.MyFriendProfile.UserName + Resources.Friendss, "ViewMyFriendFriends", "Friendship", new { friendUserId = Model.MyFriendProfile.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName }, null)
        </td>
        <td>
            @Html.ActionLink(Resources.DeleteFriend, "DeleteFriend", "Friendship", new { friendUserId = Model.MyFriendProfile.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName }, new { onclick = "return confirm('Are you sure you want to delete ?')" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(Resources.BackToMyFriends, "Index", "Friendship", new { userName = Model.MyUserProfile.UserName },null)
            </td>
    </tr>
</table>

C#/SocialGame/SocialGame/Views/Friendship/ViewFriendshipRelation.cshtml
@model SocialGame.Web.Models.ViewModels.FriendshipRelationViewModel
@using SocialGame.Web.Resources
@Scripts.Render("~/bundles/jquery")
<h2>@Resources.FriendshipRelation? </h2>

@Html.DropDownListFor(
    x => x.SelectedRelationType,
    new SelectList(Model.RelationTypes), new  { id = "cbRelationType" }
)

@Html.ActionLink(Resources.Confirm, "ConfirmFriendshipRelation", "Friendship", new { friendUserId = Model.FriendUserId, myUserId = Model.MyUserId, myUserName = Model.MyUserName }, new { id = "confirmFriendshipActionLink" })

<script>
    $('#confirmFriendshipActionLink').click(function () {
        var relationType = $('#cbRelationType').val();       
        this.href = this.href + '&relationType=' + relationType;
    });
</script>

C#/SocialGame/SocialGame/Views/Friendship/ViewMyFriendFriends.cshtml
@model SocialGame.Web.Models.ViewModels.FriendshipViewModel
@using SocialGame.Web.Resources

<h2>@Html.DisplayFor(modelItem => Model.MyFriendProfile.UserName)  Friends</h2>
<ul>
    @foreach(SocialGame.Web.Models.UserProfile friend in Model.MyFriendFriends)
    {
        <li>@Html.DisplayFor(modelItem => friend.UserName)   @if(!Model.MyFriends.Any(m => m.UserName == friend.UserName) && friend.UserName != Model.MyUserProfile.UserName) { @Html.ActionLink(Resources.SendFriendInvitation, "SendFriendInvitation", "Friendship", new { friendUserId = friend.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName }, null) }
            <p></p>
        </li>     
    }
</ul>

@Html.ActionLink(Resources.BackToMyFriends, "Index", "Friendship", new { userName = Model.MyUserProfile.UserName },null)

C#/SocialGame/SocialGame/Views/Friendship/ViewUserProfile.cshtml
@model SocialGame.Web.Models.ViewModels.FriendshipViewModel
@using SocialGame.Web.Resources

<h2>@Model.MyFriendRequestProfile.UserName @Resources.Profile</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendRequestProfile.FirstName)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendRequestProfile.FirstName)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendRequestProfile.LastName)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendRequestProfile.LastName)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendRequestProfile.Country)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendRequestProfile.Country)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendRequestProfile.City)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendRequestProfile.City)
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MyFriendRequestProfile.Mood.Description)
        </th>
        <td>
            @Html.DisplayFor(model => model.MyFriendRequestProfile.Mood.Description)
        </td>
    </tr>
    <tr>
        <td></td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(Resources.AcceptFriendship, "AcceptFriendRequest", "Friendship", new { friendUserId = Model.MyFriendRequestProfile.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName }, null)
        </td>
        <td>
            @Html.ActionLink(Resources.IgnoreFriendship, "IgnoreFriendRequest", "Friendship", new { friendUserId = Model.MyFriendRequestProfile.UserId, myUserId = Model.MyUserProfile.UserId, myUserName = Model.MyUserProfile.UserName }, null)
        </td>
    </tr>
    <tr>
        <td>
            @Html.ActionLink(Resources.BackToMyFriends, "Index", "Friendship", new { userName = Model.MyUserProfile.UserName }, null)
        </td>
    </tr>
</table>